# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Beer, Wings, and Professional Things
description: >
  We are a group of young professional looking to meet new people while
  participating in events locally in Sarnia, ON.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bwpt.beer" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
